name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        # v0.11.0
        uses: "pascalgn/automerge-action@eb9575adbe8c16386ad6a33ffc74812bfd530f90"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "rebase"
          UPDATE_METHOD: "rebase"
          MERGE_DELETE_BRANCH: true
          MERGE_RETRIES: "360"
          MERGE_RETRY_SLEEP: "10000"
